/**
 * ADN 3.0 API
 * Esta es la especificcion para el API del Sitema ADN en su version 3.0 La audiencia de este API es PRIVADA, es decir, solamente para desarrollos internos. NO se debe utilizar por externos o asociados sin la supervicion del equipo de TECINF 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: carlosribero@tinformatica.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

'use strict';
import * as models from './models';

export interface Cliente {
    

    /**
     * Identificador del Cliente
     */
    id?: string;

    /**
     * Codigo de Cliente
     */
    codigo?: string;

    /**
     * Nombre del Cliente
     */
    nombre?: string;

    /**
     * Cliente activo/desactivo
     */
    activo?: boolean;

    /**
     * Dirección del Cliente
     */
    direccion?: string;

    /**
     * Teléfonos del Cliente
     */
    telefonos?: string;

    /**
     * Email del Cliente
     */
    email?: string;

    canalDistibucion?: models.CanalDistribucion;

    municipio?: models.Municipio;

    zonaGeografica?: models.ZonaGeografica;

    /**
     * Observaciones del Cliente
     */
    observaciones?: string;
}
